server:
  port: 8084
spring:
  application:
    name: shop
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      show-details: always