server:
  port: 8083
spring:
  application:
    name: warehouse
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      show-details: always