server:
  port: 8082
spring:
  application:
    name: payment
    mail:
      host: smtp.gmail.com
      port: 587
      username: artem1978test
      password: A545575a*
      smtp:
        auth: true
        starttls:
          enable: true
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      show-details: always


