server:
  port: 8082
spring:
  application:
    name: payment
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      show-details: always